### ISSUE TITLE
Nil status returned from specific URLs

### ISSUE THREAD

**Issue by jonnyom** [lostisland/faraday#1028]
## Basic Info

* Faraday Version: 0.15.3
* Ruby Version: 2.5.5

## Issue description
Occasionally when POSTing to 3rd party URLs from our webhook service (which is using Faraday), we see `nil` statuses in our responses. This doesn't seem like expected behaviour.

## Steps to reproduce
1. Create a connection with the following configuration:
```ruby
headers = {
              "Content-Type" => "application/json",
              "Accept" => "application/json",
            }
connection = Faraday.new(ssl: { verify: true }) do |c|
              c.adapter :httpclient
              c.headers = headers
              c.options.timeout = 5
              c.options.open_timeout = 1
            end
```
2. Make a POST request to the following URL `https://intercomwebhook.gabrielramos.tk/reassign`
```ruby
connection.post(url, { test: "Testing" }.to_json)
```
3. Check the returned status. When I made did this this was the resulting Response object
```ruby
con.post(url, {hello: "hi"}.to_json)
=> #<Faraday::Response:0x0000557802a9d420
 @env=
  #<struct Faraday::Env
   method=:post,
   body=
    "<!DOCTYPE html>\r\n<html>\r\n<head>\r\n  <meta charset=\"utf-8\" />\r\n  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n  <meta name=\"robots\" content=\"noindex\">\r\n\r\n        <title data-i18n=\"[html]503_page.title\">503 \xE2\x80\x93 Servi\xC3\xA7o indispon\xC3\xADvel</title>\r\n\r\n  <link href=\"//fonts.googleapis.com/css?family=Lato:300,400,700\" rel=\"stylesheet\">\r\n  <link href=\"//static.umbler.com/umbootstrap/themes/umbler-app/dist/css/theme.min.css\" rel=\"stylesheet\" >\r\n        <link href=\"//static.umbler.com/umbler/errorpages/error-pages-v2.css\" rel=\"stylesheet\">\r\n</head>\r\n<body class=\"bg-primary wrapper\">\r\n        <div class=\"content\">\r\n                <div class=\"container\">\r\n\r\n                <h1 data-i18n=\"[html]503_page.error_title\" class=\"title text-primary-lighter mb-4\"><strong>503</strong> Servi\xC3\xA7o indispon\xC3\xADvel</h1>\r\n\r\n                        <div class=\"alert alert-info float-sm-none col-lg-7 text-xs-left mx-auto\">\r\n                                <span data-i18n=\"[html]503_page.error_help\">\r\n                                        O servidor n\xC3\xA3o pode processar a solicita\xC3\xA7\xC3\xA3o gerada pela sua aplica\xC3\xA7\xC3\xA3o no momento. Caso seja administrador da p\xC3\xA1gina, <a href=\"//app.umbler.com/\" target=\"_blank\">acessar seu painel</a> e verifique a situa\xC3\xA7\xC3\xA3o. Este site pode requerer recursos n\xC3\xA3o habilitados pelo servidor ou o servidor est\xC3\xA1 com configura\xC3\xA7\xC3\xB5es abaixo do que o site necessita.\r\n                                </span>\r\n                  </div>\r\n                </div>\r\n\r\n        </div>\r\n        <div class=\"footer\">\r\n                        <a href=\"//www.umbler.com\" taget=\"_blank\" rel=\"nofollow\">\r\n                                <svg id=\"umbler-logo\" xmlns=\"http://www.w3.org/2000/svg\" width=\"100\" viewBox=\"0 0 917.13 251.76\"><title>umbler-logo-light-bg</title><path d=\"M907.75,72.06c-22.43-.19-86.06,2.85-86.06,46.74,0,11.56,0,124.2,0,124.28a9.31,9.31,0,0,0,9.29,8.64h18.65a9.32,9.32,0,0,0,9.32-9.26V129.85c0-7.54.47-22.14,36.66-22.14,4.31,0,6.67-1.25,9.3-4.6a133.7,133.7,0,0,0,10.64-15.58C920.07,80.12,914.11,72.12,907.75,72.06Z\" fill=\"#ffffff\"/><path d=\"M784,201.66c-3.18-3.18-9.6-5-15.07.76a54.35,54.35,0,0,1-78.87-6.53c22-5.44,76-22.17,96.72-39.19,17.22-14.13,25.68-33,8.45-57C779,77,754.88,72.05,732.59,72.05c-.44,0-.88,0-1.32,0a89.43,89.43,0,0,0-55.52,20.28,90.39,90.39,0,0,0-24,30.4,89.83,89.83,0,0,0,80.87,129c14.19,0,37.42-4.68,58.43-21.67l4.94-4.95a8.79,8.79,0,0,0-.43-12Zm-88.09-80c9.68-8.83,23.53-15.31,37.64-15.31,9.39,0,19.42.86,25,7.67,2.93,3.59,2.38,9.64-.33,13.81-9.52,14.65-67.9,29.24-80,31.22A54.33,54.33,0,0,1,695.93,121.67Z\" fill=\"#ffffff\"/><path d=\"M615.71,251.75H598.44a10,10,0,0,1-10-10V10.08a10,10,0,0,1,10-10h17.27a10,10,0,0,1,10,10V241.75A10,10,0,0,1,615.71,251.75Z\" fill=\"#ffffff\"/><path d=\"M571.46,115c0-55.46-55.65-45.79-95.33-33.3V10a10,10,0,0,0-10-10H448.67a10,10,0,0,0-10,10V213.06c0,6.43,3.67,16.71,11.57,21,14.11,7.65,121.22,47.36,121.22-25.27Zm-37.58,76.43c0,7.82-2.94,14.95-9.42,19.57-12.15,8.67-35.09-.88-41.4-4.49-3.52-2-6.94-4.87-6.94-9.14V126.42c0-4.28,3.41-7.13,6.94-9.14,6.31-3.61,29.25-13.16,41.4-4.49,6.48,4.62,9.42,11.75,9.42,19.57Z\" fill=\"#ffffff\"/><path d=\"M126.58,154.6a25.21,25.21,0,0,1-48.2-4.71,24.87,24.87,0,0,1-.42-3.7,7.07,7.07,0,0,0-5.78-6.78l-12-2.12A8,8,0,0,0,50.76,145q0,.12,0,.24a52.4,52.4,0,0,0,101.73,17.68,8,8,0,0,0-6.19-10.45l-12-2.12A7,7,0,0,0,126.58,154.6Z\" fill=\"#fca4ae\"/><path d=\"M356,75.69,324.65,88.52C310.39,62.31,275.71,76,274.7,76.58l-45,16.34c-4,1.2-8.17,6-8.17,12.44V241.71a10,10,0,0,0,10,10H249a10,10,0,0,0,10-10V121.12c0-4.29,3.41-7.16,6.94-9.18,6.31-3.63,19.53-11.16,27.57-5.18,6.39,4.75,9.42,11.8,9.42,19.65V241.71a10,10,0,0,0,10,10h17.46a10,10,0,0,0,10-10V121.12c0-4.29,3.41-7.16,6.93-9.18,6.31-3.63,19.53-11.16,27.57-5.18,6,4.47,9.28,9.82,9.28,16.54V241.71a10,10,0,0,0,10,10h17.46a10,10,0,0,0,10-10V121.12C421.66,97.34,400.81,60.31,356,75.69Z\" fill=\"#ffffff\"/><path d=\"M175.55,112.82A10,10,0,0,0,169.13,124a83.62,83.62,0,0,1,1.25,14.43c0,41.66-30.48,75.43-68.09,75.43S34.2,180.09,34.2,138.44A81,81,0,0,1,45.33,97.09a10,10,0,0,0-1.49-12.24L32.76,73.77a10,10,0,0,0-15.62,1.87A121.57,121.57,0,0,0,0,138.44C0,201,45.8,251.75,102.29,251.75S204.58,201,204.58,138.44a125.5,125.5,0,0,0-2.1-22.94,10,10,0,0,0-13.27-7.65Z\" fill=\"#ffffff\"/></svg>\r\n                        </a>\r\n                        <div data-i18n=\"[html]503_page.footer\">\r\n                                Se for o administrador do site <a href=\"//help.umbler.com/hc/pt-br/articles/204980985#erro503\" target=\"_blank\" class=\"text-white\">verifique este erro em nossa central de ajuda \xE2\x86\x92</a>\r\n                        </div>\r\n         </div>\r\n</body>\r\n<script src=\"//static.umbler.com/umbler/errorpages/jquery-1.8.2.min.js\"></script>\r\n<script src=\"//static.umbler.com/umbler/errorpages/i18next-1.7.4.min.js\"></script>\r\n<script src=\"//static.umbler.com/umbler/errorpages/error_page_translate-v2.js\"></script>\r\n</html>",
   url=#<URI::HTTPS https://intercomwebhook.gabrielramos.tk/reassign>,
   request=#<struct Faraday::RequestOptions params_encoder=nil, proxy=nil, bind=nil, timeout=5, open_timeout=1, write_timeout=nil, boundary=nil, oauth=nil, context=nil>,
   request_headers={"Content-Type"=>"application/json", "Accept"=>"application/json", "User-Agent"=>"Intercom/Parrot 1.3", "Intercom-Webhook-Subscription-ID"=>"sub_id"},
   ssl=
    #<struct Faraday::SSLOptions verify=true, ca_file=nil, ca_path=nil, verify_mode=nil, cert_store=nil, client_cert=nil, client_key=nil, certificate=nil, private_key=nil, verify_depth=nil, version=nil, min_version=nil, max_version=nil>,
   parallel_manager=nil,
   params=nil,
   response=#<Faraday::Response:0x0000557802a9d420 ...>,
   response_headers={},
   status=nil,
   reason_phrase=nil>,
 @on_complete_callbacks=[]>
```

Due to the nature of our webhooks system, we can't pre-determine who we're going to send requests to, or whether things will work. Generally we rely on some sort of response to come back to tell us whether things have worked or not. I would have expected an exception to be thrown, which seems like the usual pattern here.

**Comment by technoweenie** [comment]
Hi @jonnyom, thanks for the report. I've used Faraday for webhooks, and haven't seen anything like this before. It looks like you're using the `httpclient` adapter with Faraday v0.15.3. Faraday gets the status from the adapter's response object here:

https://github.com/lostisland/faraday/blob/81274c93a21e7860dcbb334df19ece81466f1695/lib/faraday/adapter/httpclient.rb#L38-L42

https://github.com/lostisland/faraday/blob/81274c93a21e7860dcbb334df19ece81466f1695/lib/faraday/adapter.rb#L45-L52

It looks like `resp.status` is nil, where `resp` is an httpclient response. It appears this is an underlying httpclient gem issue, and not one with Faraday.

If I try this with the excon adapter instead, I get an `Excon::Error::ResponseParse` exception:

```
>> headers = {
>>               "Content-Type" => "application/json",
>>               "Accept" => "application/json",
>>             }

>> connection = Faraday.new(ssl: { verify: true }) do |c|
>>   c.adapter :excon
>>   c.headers = headers
>>   c.options.timeout = 5
>>   c.options.open_timeout = 1
>> end
>> url = "https://intercomwebhook.gabrielramos.tk/reassign"
>> connection.post(url, { test: "Testing" }.to_json)
Traceback (most recent call last):
       11: from /Users/rick/.rbenv/versions/2.5.5/bin/irb:11:in `<main>'
       10: from (irb):31
        9: from /Users/rick/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/faraday-0.15.3/lib/faraday/connection.rb:175:in `post'
        8: from /Users/rick/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/faraday-0.15.3/lib/faraday/connection.rb:387:in `run_request'
        7: from /Users/rick/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/faraday-0.15.3/lib/faraday/rack_builder.rb:143:in `build_response'
        6: from /Users/rick/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/faraday-0.15.3/lib/faraday/adapter/excon.rb:52:in `call'
        5: from /Users/rick/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/connection.rb:263:in `request'
        4: from /Users/rick/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/connection.rb:414:in `response'
        3: from /Users/rick/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/middlewares/response_parser.rb:7:in `response_call'
        2: from /Users/rick/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/response.rb:89:in `parse'
        1: from /Users/rick/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/response.rb:186:in `parse_headers'
Faraday::ConnectionFailed (malformed header (Excon::Error::ResponseParse))
```

The raised `Excon::Error::ResponseParse` tells me that the HTTP response from the server is invalid (or at least, Excon thinks it is). The `net_http` adapter raises `Net::OpenTimeout`, which seems odd.

Next was too run this through `curl`:

```
$ curl -H "Content-Type=application/json" -H "Accept=application/json" https://intercomwebhook.gabrielramos.tk/reassign -d '{"test":"Testing!"}' -v
*   Trying 177.55.116.228...
* TCP_NODELAY set
* Connected to intercomwebhook.gabrielramos.tk (177.55.116.228) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=intercomwebhook.gabrielramos.tk
*  start date: Sep 26 23:05:13 2019 GMT
*  expire date: Dec 25 23:05:13 2019 GMT
*  subjectAltName: host "intercomwebhook.gabrielramos.tk" matched cert's "intercomwebhook.gabrielramos.tk"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
> POST /reassign HTTP/1.1
> Host: intercomwebhook.gabrielramos.tk
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Length: 19
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 19 out of 19 bytes
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="robots" content="noindex">

        <title data-i18n="[html]503_page.title">503 – Serviço indisponível</title>

  <link href="//fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet">
  <link href="//static.umbler.com/umbootstrap/themes/umbler-app/dist/css/theme.min.css" rel="stylesheet" >
        <link href="//static.umbler.com/umbler/errorpages/error-pages-v2.css" rel="stylesheet">
</head>
<body class="bg-primary wrapper">
        <div class="content">
                <div class="container">

                <h1 data-i18n="[html]503_page.error_title" class="title text-primary-lighter mb-4"><strong>503</strong> Serviço indisponível</h1>

                        <div class="alert alert-info float-sm-none col-lg-7 text-xs-left mx-auto">
                                <span data-i18n="[html]503_page.error_help">
                                        O servidor não pode processar a solicitação gerada pela sua aplicação no momento. Caso seja administrador da página, <a href="//app.umbler.com/" target="_blank">acessar seu painel</a> e verifique a situação. Este site pode requerer recursos não habilitados pelo servidor ou o servidor está com configurações abaixo do que o site necessita.
                                </span>
                  </div>
                </div>

        </div>
        <div class="footer">
                        <a href="//www.umbler.com" taget="_blank" rel="nofollow">
                                <svg id="umbler-logo" xmlns="http://www.w3.org/2000/svg" width="100" viewBox="0 0 917.13 251.76"><title>umbler-logo-light-bg</title><path d="M907.75,72.06c-22.43-.19-86.06,2.85-86.06,46.74,0,11.56,0,124.2,0,124.28a9.31,9.31,0,0,0,9.29,8.64h18.65a9.32,9.32,0,0,0,9.32-9.26V129.85c0-7.54.47-22.14,36.66-22.14,4.31,0,6.67-1.25,9.3-4.6a133.7,133.7,0,0,0,10.64-15.58C920.07,80.12,914.11,72.12,907.75,72.06Z" fill="#ffffff"/><path d="M784,201.66c-3.18-3.18-9.6-5-15.07.76a54.35,54.35,0,0,1-78.87-6.53c22-5.44,76-22.17,96.72-39.19,17.22-14.13,25.68-33,8.45-57C779,77,754.88,72.05,732.59,72.05c-.44,0-.88,0-1.32,0a89.43,89.43,0,0,0-55.52,20.28,90.39,90.39,0,0,0-24,30.4,89.83,89.83,0,0,0,80.87,129c14.19,0,37.42-4.68,58.43-21.67l4.94-4.95a8.79,8.79,0,0,0-.43-12Zm-88.09-80c9.68-8.83,23.53-15.31,37.64-15.31,9.39,0,19.42.86,25,7.67,2.93,3.59,2.38,9.64-.33,13.81-9.52,14.65-67.9,29.24-80,31.22A54.33,54.33,0,0,1,695.93,121.67Z" fill="#ffffff"/><path d="M615.71,251.75H598.44a10,10,0,0,1-10-10V10.08a10,10,0,0,1,10-10h17.27a10,10,0,0,1,10,10V241.75A10,10,0,0,1,615.71,251.75Z" fill="#ffffff"/><path d="M571.46,115c0-55.46-55.65-45.79-95.33-33.3V10a10,10,0,0,0-10-10H448.67a10,10,0,0,0-10,10V213.06c0,6.43,3.67,16.71,11.57,21,14.11,7.65,121.22,47.36,121.22-25.27Zm-37.58,76.43c0,7.82-2.94,14.95-9.42,19.57-12.15,8.67-35.09-.88-41.4-4.49-3.52-2-6.94-4.87-6.94-9.14V126.42c0-4.28,3.41-7.13,6.94-9.14,6.31-3.61,29.25-13.16,41.4-4.49,6.48,4.62,9.42,11.75,9.42,19.57Z" fill="#ffffff"/><path d="M126.58,154.6a25.21,25.21,0,0,1-48.2-4.71,24.87,24.87,0,0,1-.42-3.7,7.07,7.07,0,0,0-5.78-6.78l-12-2.12A8,8,0,0,0,50.76,145q0,.12,0,.24a52.4,52.4,0,0,0,101.73,17.68,8,8,0,0,0-6.19-10.45l-12-2.12A7,7,0,0,0,126.58,154.6Z" fill="#fca4ae"/><path d="M356,75.69,324.65,88.52C310.39,62.31,275.71,76,274.7,76.58l-45,16.34c-4,1.2-8.17,6-8.17,12.44V241.71a10,10,0,0,0,10,10H249a10,10,0,0,0,10-10V121.12c0-4.29,3.41-7.16,6.94-9.18,6.31-3.63,19.53-11.16,27.57-5.18,6.39,4.75,9.42,11.8,9.42,19.65V241.71a10,10,0,0,0,10,10h17.46a10,10,0,0,0,10-10V121.12c0-4.29,3.41-7.16,6.93-9.18,6.31-3.63,19.53-11.16,27.57-5.18,6,4.47,9.28,9.82,9.28,16.54V241.71a10,10,0,0,0,10,10h17.46a10,10,0,0,0,10-10V121.12C421.66,97.34,400.81,60.31,356,75.69Z" fill="#ffffff"/><path d="M175.55,112.82A10,10,0,0,0,169.13,124a83.62,83.62,0,0,1,1.25,14.43c0,41.66-30.48,75.43-68.09,75.43S34.2,180.09,34.2,138.44A81,81,0,0,1,45.33,97.09a10,10,0,0,0-1.49-12.24L32.76,73.77a10,10,0,0,0-15.62,1.87A121.57,121.57,0,0,0,0,138.44C0,201,45.8,251.75,102.29,251.75S204.58,201,204.58,138.44a125.5,125.5,0,0,0-2.1-22.94,10,10,0,0,0-13.27-7.65Z" fill="#ffffff"/></svg>
                        </a>
                        <div data-i18n="[html]503_page.footer">
                                Se for o administrador do site <a href="//help.umbler.com/hc/pt-br/articles/204980985#erro503" target="_blank" class="text-white">verifique este erro em nossa central de ajuda →</a>
                        </div>
         </div>
</body>
<script src="//static.umbler.com/umbler/errorpages/jquery-1.8.2.min.js"></script>
<script src="//static.umbler.com/umbler/errorpages/i18next-1.7.4.min.js"></script>
<script src="//static.umbler.com/umbler/errorpages/error_page_translate-v2.js"></script>
* TLSv1.2 (IN), TLS alert, Client hello (1):
* Connection #0 to host intercomwebhook.gabrielramos.tk left intact
</html>
```

That curl output doesn't even show any response status or headers coming from the server. It just spews out some HTML. If you can update that server to send a proper HTTP response, then you'll start getting response status values in your Faraday code. If that server is out of your control, I'd default a nil status to 500.

Judging by the HTML returned by that webhook endpoint, it's trying to return a 503 response.

Does this help?

**Comment by jonnyom** [comment]
Hey @technoweenie these are all things that we tried as well and got the same results. Glad I'm not going mad. 

Unfortunately the server's out of my control, it's a third party endpoint.

We've a default in place for this, but the nil status definitely feels odd that no exception would be raised at the library level (which felt like a standard generally).

**Comment by technoweenie** [comment]
Faraday doesn't raise exceptions based on the status by default. However, the `raise_error` middleware could be updated to check for a nil value.

https://github.com/lostisland/faraday/blob/dcae077607534a33fab8a9d52fe04144cdb39ba7/lib/faraday/response/raise_error.rb#L13-L35

**Comment by jonnyom** [comment]
That's something I was thinking, raising a `Faraday::NilStatusError` would be very useful

**Comment by technoweenie** [comment]
@jonnyom Thanks for raising this issue and providing a fix. I've just opened a PR to backport it for v0.17.1: #1064
