### ISSUE TITLE
Getting error can't modify frozen String with Faraday 0.16.2

### ISSUE THREAD

**Issue by khaiql** [lostisland/faraday#1048]
## Basic Info

* Faraday Version: 0.16.2
* Ruby Version: 2.6.2

## Issue description
After pumping faraday from 0.15.4 to 0.16.2, I started getting error `can't modify frozen String` while accessing `ActiveStorage::RepresentationsController#show`.

Though I don't see faraday in the stack trace, but after reverting the commit, everything backs to normal, so pretty clear that faraday or its dependencies are suspicious, hence looking for support from you. 

Stacktrace
```
Exception(most recent call first)

FrozenError: can't modify frozen String
  from azure/storage/blob/blob_service.rb:68:in `force_encoding'
  from azure/storage/blob/blob_service.rb:68:in `call'
  from azure/storage/blob/blob.rb:168:in `get_blob_properties'
  from active_storage/service/azure_storage_service.rb:127:in `blob_for'
  from active_storage/service/azure_storage_service.rb:79:in `block in exist?'
  from active_support/notifications.rb:180:in `block in instrument'
  from active_support/notifications/instrumenter.rb:24:in `instrument'
  from active_support/notifications.rb:180:in `instrument'
  from active_storage/service.rb:126:in `instrument'
  from active_storage/service/azure_storage_service.rb:78:in `exist?'
  from active_storage/variant.rb:95:in `processed?'
  from active_storage/variant.rb:67:in `processed'
  from active_storage/representations_controller.rb:12:in `show'
  from action_controller/metal/basic_implicit_render.rb:6:in `send_action'
  from abstract_controller/base.rb:196:in `process_action'
  from action_controller/metal/rendering.rb:30:in `process_action'
  from abstract_controller/callbacks.rb:42:in `block in process_action'
  from active_support/callbacks.rb:112:in `block in run_callbacks'
  from raven/integrations/rails/controller_transaction.rb:7:in `block in included'
  from active_support/callbacks.rb:121:in `instance_exec'
  from active_support/callbacks.rb:121:in `block in run_callbacks'
  from active_support/callbacks.rb:139:in `run_callbacks'
  from abstract_controller/callbacks.rb:41:in `process_action'
  from action_controller/metal/rescue.rb:22:in `process_action'
  from action_controller/metal/instrumentation.rb:33:in `block in process_action'
  from active_support/notifications.rb:180:in `block in instrument'
  from active_support/notifications/instrumenter.rb:24:in `instrument'
  from active_support/notifications.rb:180:in `instrument'
  from action_controller/metal/instrumentation.rb:32:in `process_action'
  from action_controller/metal/params_wrapper.rb:245:in `process_action'
  from active_record/railties/controller_runtime.rb:27:in `process_action'
  from abstract_controller/base.rb:136:in `process'
  from action_view/rendering.rb:39:in `process'
  from action_controller/metal.rb:191:in `dispatch'
  from action_controller/metal.rb:252:in `dispatch'
  from action_dispatch/routing/route_set.rb:51:in `dispatch'
  from action_dispatch/routing/route_set.rb:33:in `serve'
  from action_dispatch/journey/router.rb:49:in `block in serve'
  from action_dispatch/journey/router.rb:32:in `each'
  from action_dispatch/journey/router.rb:32:in `serve'
  from action_dispatch/routing/route_set.rb:837:in `call'
  from omniauth/strategy.rb:192:in `call!'
  from omniauth/strategy.rb:169:in `call'
  from rack/tracker.rb:40:in `call'
  from warden/manager.rb:36:in `block in call'
  from warden/manager.rb:34:in `catch'
  from warden/manager.rb:34:in `call'
  from rack/tempfile_reaper.rb:15:in `call'
  from rack/etag.rb:25:in `call'
  from rack/conditional_get.rb:25:in `call'
  from rack/head.rb:12:in `call'
  from action_dispatch/http/content_security_policy.rb:18:in `call'
  from rack/session/abstract/id.rb:232:in `context'
  from rack/session/abstract/id.rb:226:in `call'
  from action_dispatch/middleware/cookies.rb:648:in `call'
  from action_dispatch/middleware/callbacks.rb:27:in `block in call'
  from active_support/callbacks.rb:101:in `run_callbacks'
  from action_dispatch/middleware/callbacks.rb:26:in `call'
  from action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
  from action_dispatch/middleware/debug_exceptions.rb:32:in `call'
  from action_dispatch/middleware/show_exceptions.rb:33:in `call'
  from lograge/rails_ext/rack/logger.rb:15:in `call_app'
  from rails/rack/logger.rb:26:in `block in call'
  from active_support/tagged_logging.rb:80:in `block in tagged'
  from active_support/tagged_logging.rb:28:in `tagged'
  from active_support/tagged_logging.rb:80:in `tagged'
  from rails/rack/logger.rb:26:in `call'
  from action_dispatch/middleware/remote_ip.rb:81:in `call'
  from request_store/middleware.rb:19:in `call'
  from action_dispatch/middleware/request_id.rb:27:in `call'
  from rack/method_override.rb:22:in `call'
  from rack/runtime.rb:22:in `call'
  from active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
  from action_dispatch/middleware/executor.rb:14:in `call'
  from action_dispatch/middleware/static.rb:126:in `call'
  from rack/sendfile.rb:111:in `call'
  from action_dispatch/middleware/host_authorization.rb:77:in `call'
  from raven/integrations/rack.rb:51:in `call'
  from rails/engine.rb:526:in `call'
  from puma/configuration.rb:228:in `call'
  from puma/server.rb:670:in `handle_request'
  from puma/server.rb:473:in `process_client'
  from puma/server.rb:331:in `block in run'
  from puma/thread_pool.rb:134:in `block in spawn_thread'
```

## Steps to reproduce

Things I used:
- Rails 6.0
- ActiveStorage with Azure Blob service
- Use faraday 0.16.2
- Try to access to an attachment would result in error

**Comment by happy-dariush** [comment]
It seems like this [PR](https://github.com/lostisland/faraday/pull/1039) should fix the issues described above.
> @zspencer you might have to point at the 0.16.x branch in your gemfile if you need it right now, until the maintainers have a chance to release 0.16.3
https://github.com/lostisland/faraday/issues/1038#issuecomment-537727323

**Comment by iMacTia** [comment]
Hello everyone, we are really sorry for all the disruptions caused by the v0.16.x releases.
We've just performed a ROLLBACK RELEASE v0.17.0 which follows directly the latest working release v0.15.4.
Please update to that version to solve the backwards-compatibility issues.
More info here: https://github.com/lostisland/faraday/releases/tag/v0.17.0
