### ISSUE TITLE
rack + rack-test: Test suite fails on master

### ISSUE THREAD

**Issue by olleolleolle** [lostisland/faraday#1119]
TL;DR: `undefined method 'split' for nil:NilClass` on tests about rack adapter.

## Basic Info

* Faraday Version: current master
* Ruby Version: any

## Issue description

There seems to be a rack-test/rack mismatch.

```
     NoMethodError:
       undefined method `split' for nil:NilClass
     Shared Example Group: "a request method" called from ./spec/support/shared_examples/adapter.rb:101
     Shared Example Group: "adapter examples" called from ./spec/support/shared_examples/adapter.rb:8
     Shared Example Group: "an adapter" called from ./spec/faraday/adapter/rack_spec.rb:7
     # /home/runner/.rvm/gems/ruby-2.5.7/gems/rack-2.1.1/lib/rack/mock.rb:236:in `identify_cookie_attributes'
     # /home/runner/.rvm/gems/ruby-2.5.7/gems/rack-2.1.1/lib/rack/mock.rb:220:in `block in parse_cookies_from_header'
     # /home/runner/.rvm/gems/ruby-2.5.7/gems/rack-2.1.1/lib/rack/mock.rb:218:in `each'
     # /home/runner/.rvm/gems/ruby-2.5.7/gems/rack-2.1.1/lib/rack/mock.rb:218:in `parse_cookies_from_header'
     # /home/runner/.rvm/gems/ruby-2.5.7/gems/rack-2.1.1/lib/rack/mock.rb:169:in `initialize'
     # /home/runner/.rvm/gems/ruby-2.5.7/gems/rack-test-1.1.0/lib/rack/mock_session.rb:31:in `new'
     # /home/runner/.rvm/gems/ruby-2.5.7/gems/rack-test-1.1.0/lib/rack/mock_session.rb:31:in `request'
     # /home/runner/.rvm/gems/ruby-2.5.7/gems/rack-test-1.1.0/lib/rack/test.rb:266:in `process_request'
     # /home/runner/.rvm/gems/ruby-2.5.7/gems/rack-test-1.1.0/lib/rack/test.rb:119:in `request'
```

Source: https://github.com/lostisland/faraday/runs/400710918#step:8:3379

## Steps to reproduce

Run the test suite from current master.

Or, watch the CI output linked above.

**Comment by olleolleolle** [comment]
Thanks a lot!
