### ISSUE TITLE
16 tests fail with NoMethodError:  undefined method `split' for nil:NilClass

### ISSUE THREAD

**Issue by pravi** [lostisland/faraday#1126]
## Basic Info

* Faraday Version: 1.0.0
* Ruby Version: 2.5 and 2.7

## Issue description

16 tests fail with same error messages also fails in ci https://github.com/lostisland/faraday/runs/402681945
```
16) Faraday::Adapter::Rack behaves like an adapter with SSL enabled #put behaves like a request method handles headers with multiple values
      Failure/Error: @session.request(env[:url].to_s, rack_env)
      
      NoMethodError:
        undefined method `split' for nil:NilClass
      Shared Example Group: "a request method" called from ./spec/support/shared_examples/adapter.rb:94
      Shared Example Group: "adapter examples" called from ./spec/support/shared_examples/adapter.rb:8
      Shared Example Group: "an adapter" called from ./spec/faraday/adapter/rack_spec.rb:7
      # ./vendor/bundle/ruby/2.7.0/gems/rack-2.1.2/lib/rack/mock.rb:236:in `identify_cookie_attributes'
      # ./vendor/bundle/ruby/2.7.0/gems/rack-2.1.2/lib/rack/mock.rb:220:in `block in parse_cookies_from_header'
      # ./vendor/bundle/ruby/2.7.0/gems/rack-2.1.2/lib/rack/mock.rb:218:in `each'
      # ./vendor/bundle/ruby/2.7.0/gems/rack-2.1.2/lib/rack/mock.rb:218:in `parse_cookies_from_header'
      # ./vendor/bundle/ruby/2.7.0/gems/rack-2.1.2/lib/rack/mock.rb:169:in `initialize'
      # ./vendor/bundle/ruby/2.7.0/gems/rack-test-1.1.0/lib/rack/mock_session.rb:31:in `new'
      # ./vendor/bundle/ruby/2.7.0/gems/rack-test-1.1.0/lib/rack/mock_session.rb:31:in `request'
      # ./vendor/bundle/ruby/2.7.0/gems/rack-test-1.1.0/lib/rack/test.rb:266:in `process_request'
      # ./vendor/bundle/ruby/2.7.0/gems/rack-test-1.1.0/lib/rack/test.rb:119:in `request'
      # ./lib/faraday/adapter/rack.rb:63:in `execute_request'
      # ./lib/faraday/adapter/rack.rb:47:in `call'
      # ./lib/faraday/response.rb:11:in `call'
      # ./lib/faraday/request/url_encoded.rb:23:in `call'
      # ./lib/faraday/request/multipart.rb:25:in `call'
      # ./lib/faraday/rack_builder.rb:154:in `build_response'
      # ./lib/faraday/connection.rb:492:in `run_request'
      # ./lib/faraday/connection.rb:279:in `put'
      # ./spec/support/shared_examples/request_method.rb:5:in `public_send'
      # ./spec/support/shared_examples/request_method.rb:5:in `block (2 levels) in <top (required)>'
      # ./spec/support/shared_examples/request_method.rb:17:in `block (2 levels) in <top (required)>'

Finished in 7.68 seconds (files took 0.98737 seconds to load)
2693 examples, 16 failures
```

## Steps to reproduce
If possible, please provide the steps to reproduce the issue.

## CHECKLIST (delete before creating the issue)
* If you're not reporting a bug/issue, you can ignore this whole template.
* Are you using the latest Faraday version? If not, please check the [Releases](https://github.com/lostisland/faraday/releases) page to see if the issue has already been fixed.
* Provide the Faraday and Ruby Version you're using while experiencing the issue.
* Fill the `Issue description` and `Steps to Reproduce` sections.
* Delete this checklist before posting the issue.

**Comment by olleolleolle** [comment]
Thanks!

This is a duplicate of #1119, and this issue can be closed.

**Comment by pravi** [comment]
Closing as duplicate.
