### ISSUE TITLE
Module not found marshmallow.compat

### ISSUE THREAD

**Issue by cixafo** [lostisland/faraday#1131]
## Basic Info

* Faraday Version: 3.10.2-0kali1
* Ruby Version: 2.5.7p206

## Issue description
I'm upgrading my debian with apt and when metasploit package is upgrading, it through an error in faraday as 

Setting up faraday (3.10.2-0kali1) ...
Traceback (most recent call last):
  File "/usr/bin/faraday-manage", line 11, in <module>
    load_entry_point('faradaysec==3.10.2', 'console_scripts', 'faraday-manage')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/faraday/manage.py", line 43, in <module>
    from faraday.server.commands.faraday_schema_display import DatabaseSchema
  File "/usr/lib/python3/dist-packages/faraday/server/commands/faraday_schema_display.py", line 17, in <module>
    from faraday.server import models
  File "/usr/lib/python3/dist-packages/faraday/server/models.py", line 46, in <module>
    from faraday.server.fields import FaradayUploadedFile, JSONType
  File "/usr/lib/python3/dist-packages/faraday/server/fields.py", line 20, in <module>
    from webargs.core import ValidationError
  File "/usr/lib/python3/dist-packages/webargs/__init__.py", line 7, in <module>
    from webargs.core import dict2schema, ValidationError
  File "/usr/lib/python3/dist-packages/webargs/core.py", line 23, in <module>
    from marshmallow.compat import iteritems
ModuleNotFoundError: No module named 'marshmallow.compat'
dpkg: error processing package faraday (--configure):
 installed faraday package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of python-faraday:
 python-faraday depends on faraday; however:
  Package faraday is not configured yet.

dpkg: error processing package python-faraday (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 faraday
 python-faraday
needrestart is being skipped since dpkg has failed
Scanning application launchers
Updating active launchers
Done
E: Sub-process /usr/bin/dpkg returned an error code (1)

I've tried installing marshmallow with pip but it shows requirement satisfies and still throw the error.

**Comment by olleolleolle** [comment]
Hello, this repository is not a pen-test tool.

This Python project _is_:
https://github.com/infobyte/faraday

I will close this Issue, and hope that the above helps!
