### ISSUE TITLE
faraday 1.0.0/1.1.0 test failure:  Failure/Error: expect(conn.proxy.host).to eq('proxy.com')

### ISSUE THREAD

**Issue by pravi** [lostisland/faraday#1212]
## Basic Info

* Faraday Version: 1.1.0
* Ruby Version: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux-gnu]

## Issue description
```
Failures:

  1) Faraday::Connection proxy support allows when url not in no proxy list
     Failure/Error: expect(conn.proxy.host).to eq('proxy.com')
     
     NoMethodError:
       undefined method `host' for nil:NilClass
     # ./spec/faraday/connection_spec.rb:432:in `block (4 levels) in <top (required)>'
     # ./spec/support/helper_methods.rb:60:in `with_env'
     # ./spec/faraday/connection_spec.rb:430:in `block (3 levels) in <top (required)>'
     # ./vendor/ruby/2.7.0/gems/webmock-3.10.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  2) Faraday::Connection proxy support performing a request dynamically checks proxy
     Failure/Error: expect(req.options.proxy.uri.host).to eq('proxy.com')
     
     NoMethodError:
       undefined method `uri' for nil:NilClass
     # ./spec/faraday/connection_spec.rb:522:in `block (6 levels) in <top (required)>'
     # ./lib/faraday/connection.rb:200:in `block in get'
     # ./lib/faraday/connection.rb:489:in `block in run_request'
     # ./lib/faraday/connection.rb:506:in `block in build_request'
     # ./lib/faraday/request.rb:57:in `block in create'
     # ./lib/faraday/request.rb:56:in `tap'
     # ./lib/faraday/request.rb:56:in `create'
     # ./lib/faraday/connection.rb:502:in `build_request'
     # ./lib/faraday/connection.rb:484:in `run_request'
     # ./lib/faraday/connection.rb:198:in `get'
     # ./spec/faraday/connection_spec.rb:521:in `block (5 levels) in <top (required)>'
     # ./spec/support/helper_methods.rb:60:in `with_env'
     # ./spec/faraday/connection_spec.rb:517:in `block (4 levels) in <top (required)>'
     # ./vendor/ruby/2.7.0/gems/webmock-3.10.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

Finished in 12.05 seconds (files took 1.12 seconds to load)
2732 examples, 2 failures

Failed examples:

rspec ./spec/faraday/connection_spec.rb:429 # Faraday::Connection proxy support allows when url not in no proxy list
rspec ./spec/faraday/connection_spec.rb:516 # Faraday::Connection proxy support performing a request dynamically checks proxy

Randomized with seed 8

```

## Steps to reproduce

Just the usual steps (bundle install --path vendor & bundle exec rake). First noticed in debian, these tests were passing earlier.

Earlier build that passed https://buildd.debian.org/status/fetch.php?pkg=ruby-faraday&arch=all&ver=1.0.0-1&stamp=1581007416&raw=0

**Comment by pravi** [comment]
Though I cannot reproduce this error in other machines.

**Comment by olleolleolle** [comment]
@pravi Thanks, both for reporting & quickly validating.
