### ISSUE TITLE
rspec testsuite error with ruby3.4.0dev

### ISSUE THREAD

**Issue by mtasaka** [lostisland/faraday#1602]
Testing with `ruby 3.4.0dev (2024-12-01 master 96fac34797) +PRISM [x86_64-linux]`
https://github.com/ruby/ruby/commit/96fac34797b3cf5d020cef8546cc37c6733c88f2

faraday git head 
https://github.com/lostisland/faraday/commit/f9f4ce5bc13278ee1e63c37a50303c640b45065d
causes rspec testsuite failure like below.

```
$ bundle exec rake

Failures:

  1) Faraday::Error.initialize with response hash is expected to eq "#<Faraday::Error response={:status=>400}>"
     Failure/Error: it { expect(subject.inspect).to eq('#<Faraday::Error response={:status=>400}>') }
     
       expected: "#<Faraday::Error response={:status=>400}>"
            got: "#<Faraday::Error response={status: 400}>"
     
       (compared using ==)
     # ./spec/faraday/error_spec.rb:27:in 'block (4 levels) in <top (required)>'
     # /builddir/.local/share/gem/ruby/gems/webmock-3.24.0/lib/webmock/rspec.rb:39:in 'block (2 levels) in <top (required)>'

  2) Faraday::Error.initialize with exception string and response hash is expected to eq "#<Faraday::Error response={:status=>400}>"
     Failure/Error: it { expect(subject.inspect).to eq('#<Faraday::Error response={:status=>400}>') }
     
       expected: "#<Faraday::Error response={:status=>400}>"
            got: "#<Faraday::Error response={status: 400}>"
     
       (compared using ==)
     # ./spec/faraday/error_spec.rb:64:in 'block (4 levels) in <top (required)>'
     # /builddir/.local/share/gem/ruby/gems/webmock-3.24.0/lib/webmock/rspec.rb:39:in 'block (2 levels) in <top (required)>'

Finished in 2.01 seconds (files took 0.8455 seconds to load)
593 examples, 2 failures

Failed examples:

rspec ./spec/faraday/error_spec.rb:27 # Faraday::Error.initialize with response hash is expected to eq "#<Faraday::Error response={:status=>400}>"
rspec ./spec/faraday/error_spec.rb:64 # Faraday::Error.initialize with exception string and response hash is expected to eq "#<Faraday::Error response={:status=>400}>"
```

**Comment by olleolleolle** [comment]
@mtasaka Thanks for the report! Would you like to make a PR with a conditional step in the test suite, checking differently for Ruby 3.4+?

**Comment by iMacTia** [comment]
Or bonus points if we can change the test so that it doesn't rely on `inspect` and works with all Ruby versions 😄
