### ISSUE TITLE
Faraday::ParsingError with gzip content

### ISSUE THREAD

**Issue by amitpatelx** [lostisland/faraday#1603]
## Basic Info

* Faraday Version: 2.12.0
* Ruby Version: ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [x86_64-linux]

### Client
```ruby
class Client
  def connection(base_url:)
    @connection ||= Faraday.new(url: base_url) do |conn|
      conn.request :json
      conn.response :json
      conn.response :raise_error
      conn.response :logger
      conn.adapter Faraday.default_adapter
    end
  end
end
```

### Log
```ruby
I, [2024-12-02T04:49:47.869315 #21060]  INFO -- request: GET https://example.com/hotel_rooms?adult_count=1&check_in_date=2024-12-03&check_out_date=2024-12-04&currency=JPY&hotel_id=rndm&locale=en-US&room_count=1&source_market=JP
I, [2024-12-02T04:49:47.869417 #21060]  INFO -- request: Content-Type: "application/json"
Accept-Encoding: "gzip"
X-Api-Key: "<API KEY>"
User-Agent: "Platform API Client"
I, [2024-12-02T04:49:48.688156 #21060]  INFO -- response: Status 200
I, [2024-12-02T04:49:48.688243 #21060]  INFO -- response: content-type: "application/json"
x-ratelimit-remaining-minute: "1499"
ratelimit-limit: "1500"
ratelimit-remaining: "1499"
ratelimit-reset: "12"
x-ratelimit-limit-minute: "1500"
cache-control: "no-cache, no-store, must-revalidate"
content-encoding: "gzip"
expires: "0"
pragma: "no-cache"
date: "Mon, 02 Dec 2024 04:49:48 GMT"
content-security-policy: "frame-ancestors 'none'"
x-content-type-options: "nosniff"
x-frame-options: "SAMEORIGIN"
x-xss-protection: "1; mode=block"
strict-transport-security: "max-age=15724800; includeSubDomains"
via: "1.1 google"
alt-svc: "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"
transfer-encoding: "chunked"
/home/vscode/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/faraday-2.12.0/lib/faraday/response/json.rb:36:in `parse': Empty input (after ) at line 1, column 1 [parse.c:1062] in '\x8 (Faraday::ParsingError)
        from /home/vscode/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/faraday-2.12.0/lib/faraday/response/json.rb:36:in `public_send'
        from /home/vscode/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/faraday-2.12.0/lib/faraday/response/json.rb:36:in `parse'
        from /home/vscode/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/faraday-2.12.0/lib/faraday/response/json.rb:26:in `process_response'
        from /home/vscode/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/faraday-2.12.0/lib/faraday/response/json.rb:19:in `on_complete'
        from /home/vscode/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/faraday-2.12.0/lib/faraday/middleware.rb:57:in `block in call'
        from /home/vscode/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/faraday-2.12.0/lib/faraday/response.rb:42:in `on_complete'
        from /home/vscode/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/faraday-2.12.0/lib/faraday/middleware.rb:56:in `call'
        from /home/vscode/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/faraday-2.12.0/lib/faraday/middleware.rb:56:in `call'
        from /home/vscode/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/faraday-2.12.0/lib/faraday/rack_builder.rb:152:in `build_response'
        from /home/vscode/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/faraday-2.12.0/lib/faraday/connection.rb:452:in `run_request'
        from /home/vscode/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/faraday-2.12.0/lib/faraday/connection.rb:200:in `get'
        from /workspaces/platform/lib/ota/requests/base.rb:19:in `public_send'
        from /workspaces/platform/lib/ota/requests/base.rb:19:in `call'
        from /workspaces/platform/lib/ota/requests/base.rb:13:in `call'
        from /workspaces/platform/lib/ota/requests.rb:57:in `hotel_rooms'
        from (platform):1:in `<main>'
        ... 31 levels...
/home/vscode/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/faraday-2.12.0/lib/faraday/response/json.rb:36:in `parse': Empty input (after ) at line 
```

If I remove `conn.response :json` line, I get the full response body and able to parse with `JSON.parse` elsewhere.

I tried using https://github.com/bodrovis/faraday-gzip but it doesn't help.

```ruby
require 'faraday/gzip' # <<<< Added

class Client
  def connection(base_url:)
    @connection ||= Faraday.new(url: base_url) do |conn|
      conn.request :gzip  # <<<< Added
      conn.request :json
      conn.response :json
      conn.response :raise_error
      conn.response :logger
      conn.adapter Faraday.default_adapter
    end
  end
end
```

## Steps to reproduce
Call a JSON API that returns gzip content

**Comment by olleolleolle** [comment]
Perhaps you can try ordering it a little differently?

I think of this ordering as "treat it first as JSON, then as gzip".

```ruby
      conn.request :gzip  # <<<< Added
      conn.request :json
      conn.response :json
```

Perhaps we wish more of a 

```ruby
      conn.request :json
      conn.response :json
      conn.request :gzip  # <<<< Added, _earlier_ in the process than :json 
```

**Comment by amitpatelx** [comment]
@olleolleolle awesome! It worked. Thanks.

I am curious about why JSON should be prioritize over gzip.

> I think of this ordering as "treat it first as JSON, then as gzip".

**Comment by olleolleolle** [comment]
@amitpatelx Thanks for confirming! I will close the Issue.

And! I will refer you to [this Middleware picture in the documentation](https://lostisland.github.io/faraday/#/middleware/index?id=how-it-works) – which tries to show how the order does matter. Hope this helps!
