### ISSUE TITLE
Faraday getting ConnectionFailed for post requests

### ISSUE THREAD

**Issue by nareshchilukuru** [lostisland/faraday#442]
When I am trying to make post request getting below error

```
Faraday::ConnectionFailed (wrong status line: "<html>"):
Request Details:
extra_parameters = {}
backtrace = "/home/vinod/projects/synapsify-webapp/app/controllers/reports_controller.rb:20:in `index'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/actionpack-4.1.0/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/actionpack-4.1.0/lib/abstract_controller/base.rb:189:in `process_action'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/actionpack-4.1.0/lib/action_controller/metal/rendering.rb:10:in `process_action'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/actionpack-4.1.0/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/activesupport-4.1.0/lib/active_support/callbacks.rb:113:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/activesupport-4.1.0/lib/active_support/callbacks.rb:113:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/activesupport-4.1.0/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/activesupport-4.1.0/lib/active_support/callbacks.rb:149:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/activesupport-4.1.0/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/activesupport-4.1.0/lib/active_support/callbacks.rb:149:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/activesupport-4.1.0/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/activesupport-4.1.0/lib/active_support/callbacks.rb:149:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/activesupport-4.1.0/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/activesupport-4.1.0/lib/active_support/callbacks.rb:166:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/activesupport-4.1.0/lib/active_support/callbacks.rb:166:in `block in halting'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/activesupport-4.1.0/lib/active_support/callbacks.rb:229:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/activesupport-4.1.0/lib/active_support/callbacks.rb:229:in `block in halting'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/activesupport-4.1.0/lib/active_support/callbacks.rb:299:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/activesupport-4.1.0/lib/active_support/callbacks.rb:299:in `block (2 levels) in halting'
/home/vinod/projects/synapsify-webapp/app/controllers/application_controller.rb:24:in `set_current_user'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/activesupport-4.1.0/lib/active_support/callbacks.rb:424:in `block in make_lambda'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/activesupport-4.1.0/lib/active_support/callbacks.rb:298:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/activesupport-4.1.0/lib/active_support/callbacks.rb:298:in `block in halting'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/activesupport-4.1.0/lib/active_support/callbacks.rb:229:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/activesupport-4.1.0/lib/active_support/callbacks.rb:229:in `block in halting'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/activesupport-4.1.0/lib/active_support/callbacks.rb:229:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/activesupport-4.1.0/lib/active_support/callbacks.rb:229:in `block in halting'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/activesupport-4.1.0/lib/active_support/callbacks.rb:166:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/activesupport-4.1.0/lib/active_support/callbacks.rb:166:in `block in halting'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/activesupport-4.1.0/lib/active_support/callbacks.rb:166:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/activesupport-4.1.0/lib/active_support/callbacks.rb:166:in `block in halting'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/activesupport-4.1.0/lib/active_support/callbacks.rb:166:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/activesupport-4.1.0/lib/active_support/callbacks.rb:166:in `block in halting'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/activesupport-4.1.0/lib/active_support/callbacks.rb:86:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/activesupport-4.1.0/lib/active_support/callbacks.rb:86:in `run_callbacks'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/actionpack-4.1.0/lib/abstract_controller/callbacks.rb:19:in `process_action'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/actionpack-4.1.0/lib/action_controller/metal/rescue.rb:29:in `process_action'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/actionpack-4.1.0/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/activesupport-4.1.0/lib/active_support/notifications.rb:159:in `block in instrument'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/activesupport-4.1.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/activesupport-4.1.0/lib/active_support/notifications.rb:159:in `instrument'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/actionpack-4.1.0/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/actionpack-4.1.0/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/activerecord-4.1.0/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/actionpack-4.1.0/lib/abstract_controller/base.rb:136:in `process'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/actionview-4.1.0/lib/action_view/rendering.rb:30:in `process'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/actionpack-4.1.0/lib/action_controller/metal.rb:195:in `dispatch'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/actionpack-4.1.0/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/actionpack-4.1.0/lib/action_controller/metal.rb:231:in `block in action'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/actionpack-4.1.0/lib/action_dispatch/routing/route_set.rb:80:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/actionpack-4.1.0/lib/action_dispatch/routing/route_set.rb:80:in `dispatch'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/actionpack-4.1.0/lib/action_dispatch/routing/route_set.rb:48:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/actionpack-4.1.0/lib/action_dispatch/journey/router.rb:71:in `block in call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/actionpack-4.1.0/lib/action_dispatch/journey/router.rb:59:in `each'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/actionpack-4.1.0/lib/action_dispatch/journey/router.rb:59:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/actionpack-4.1.0/lib/action_dispatch/routing/route_set.rb:676:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/rack-pjax-0.7.0/lib/rack/pjax.rb:12:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/newrelic_rpm-3.8.1.221/lib/new_relic/rack/error_collector.rb:55:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/newrelic_rpm-3.8.1.221/lib/new_relic/rack/agent_hooks.rb:32:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/newrelic_rpm-3.8.1.221/lib/new_relic/rack/browser_monitoring.rb:27:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/newrelic_rpm-3.8.1.221/lib/new_relic/rack/developer_mode.rb:45:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/rack-1.5.2/lib/rack/conditionalget.rb:25:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/remotipart-1.2.1/lib/remotipart/middleware.rb:27:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/actionpack-4.1.0/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/actionpack-4.1.0/lib/action_dispatch/middleware/flash.rb:254:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/actionpack-4.1.0/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/activerecord-4.1.0/lib/active_record/query_cache.rb:36:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/activerecord-4.1.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/activerecord-4.1.0/lib/active_record/migration.rb:380:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/actionpack-4.1.0/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/activesupport-4.1.0/lib/active_support/callbacks.rb:82:in `run_callbacks'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/actionpack-4.1.0/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/actionpack-4.1.0/lib/action_dispatch/middleware/reloader.rb:73:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/actionpack-4.1.0/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/actionpack-4.1.0/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/actionpack-4.1.0/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/railties-4.1.0/lib/rails/rack/logger.rb:38:in `call_app'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/railties-4.1.0/lib/rails/rack/logger.rb:20:in `block in call'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/activesupport-4.1.0/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/home/vinod/.rvm/gems/ruby-2.1.2@rails-devise-pundit/gems/activesupport-4.1.0/lib/active_support/tagged_logging.rb:26:in `tagged'"
```

```ruby
extra_parameters = {:exception = backtrace }

@conn = Faraday.new(:url => @host) do |faraday|
	faraday.params[:auth_token] = @auth_token
	faraday.request  :url_encoded             # form-encode POST params
	faraday.response :logger                  # log requests to STDOUT
	faraday.adapter  Faraday.default_adapter  # make requests with Net::HTTP
end

raw_response = @conn.post do |req|
	req.url "/#{model}.json"
	req.headers['Content-Type'] = 'application/json'
	req.params.merge!(extra_parameters)
end
```

But when am try with short message of exception it is making request without any issues
eg: extra_parameters = {:exception = "small exception message" }

**Comment by technoweenie** [comment]
The message `wrong status line: "<html>"` makes it sound like the server is returning an invalid response.

You probably don't want to send a long backtrace in `params` (which gets encoded to the URL query).  Have you tried something like this?

```ruby
@conn = Faraday.new(:url => @host) do |faraday|
    faraday.params[:auth_token] = @auth_token
    faraday.request  :url_encoded             # form-encode POST params
    faraday.response :logger                  # log requests to STDOUT
    faraday.adapter  Faraday.default_adapter  # make requests with Net::HTTP
end

raw_response = @conn.post do |req|
    req.url "/#{model}.json"
    req.headers['Content-Type'] = 'application/json'
    req.body = {:exception = backtrace}.to_json
end
```

**Comment by mislav** [comment]
Closing since this looks like a server error.
