### ISSUE TITLE
Registering external adapter breaks internal ones

### ISSUE THREAD

**Issue by lacostej** [lostisland/faraday#516]
I've been toying with hardening the SSL configuration of the default adapter.

The result is in: https://github.com/lacostej/spaceship/commit/1240469ea481e8feeb12e877205c666dca782f01

It works fine. But I have a problem with the way registering adapters work. In particular, adding an external adapter requires to write convoluted code:
`````
 Faraday::Adapter.register_middleware File.expand_path(File.dirname(__FILE__)),
                                       secure_net_http: [:SecureNetHttp, 'secure_net_http']
```````
And this breaks the internal loading of existing adapters. E.g. if one tries to use the default_adapter after having loaded a custom one:

`````
       cannot load such file -- /Users/lacostej/Code/OSS/Fastlane/spaceship/lib/spaceship/net_http
     # /Users/lacostej/.rvm/gems/ruby-2.2.2/gems/faraday-0.9.1/lib/faraday.rb:223:in `require'
     # /Users/lacostej/.rvm/gems/ruby-2.2.2/gems/faraday-0.9.1/lib/faraday.rb:223:in `block in load_middleware'
     # /Users/lacostej/.rvm/gems/ruby-2.2.2/gems/faraday-0.9.1/lib/faraday.rb:197:in `middleware_mutex'
     # /Users/lacostej/.rvm/gems/ruby-2.2.2/gems/faraday-0.9.1/lib/faraday.rb:218:in `load_middleware'
     # /Users/lacostej/.rvm/gems/ruby-2.2.2/gems/faraday-0.9.1/lib/faraday.rb:188:in `lookup_middleware'
     # /Users/lacostej/.rvm/gems/ruby-2.2.2/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:203:in `use_symbol'
     # /Users/lacostej/.rvm/gems/ruby-2.2.2/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:100:in `adapter'
     # ./lib/spaceship/client.rb:77:in `block in initialize'
     # /Users/lacostej/.rvm/gems/ruby-2.2.2/gems/faraday-0.9.1/lib/faraday/connection.rb:91:in `initialize'
     # /Users/lacostej/.rvm/gems/ruby-2.2.2/gems/faraday-0.9.1/lib/faraday.rb:70:in `new'
     # /Users/lacostej/.rvm/gems/ruby-2.2.2/gems/faraday-0.9.1/lib/faraday.rb:70:in `new'
     # ./lib/spaceship/client.rb:73:in `initialize'
`````

This is because the @middleware_autoload_path is global to all registered adapters.

Before I try fixing this, please let me know if I am doing something wrong or if there's a way to register external adapters in a different way.

**Comment by lacostej** [comment]
I end up doing something like
`````
  # Faraday is really sensitive when modifying the middleware. It currently breaks the use of the
  # default adapter after having registered an external one
  # See https://github.com/lostisland/faraday/issues/516
  # I end up forcing the registration of the default adapter again, so that it resets
  def self.init_secure
    if secure?
      Faraday::Adapter.register_middleware File.expand_path(File.dirname(__FILE__)),
                                           secure_net_http: [:SecureNetHttp, 'secure_net_http']
    else
      adapter_path = Gem::Specification.find_by_name("faraday").gem_dir + '/lib/faraday/adapter'
      Faraday::Adapter.register_middleware adapter_path,
                                           net_http: [:NetHttp, 'net_http']
    end
  end
`````
to workaround the registration.

https://github.com/lacostej/spaceship/commit/0918a7a

It's an ugly work-around :)

**Comment by mislav** [comment]
You should define the adapter in your own namespace:

```rb
require "faraday"

module MyApp
  class MyAdapter < Faraday::Adapter
    # ...
  end
end

# and then register it like so:
Faraday::Adapter.register_middleware :secure_http => MyApp::MyAdapter
```

You shouldn't pass the first argument (autoload_path); that's only for internal use. Sorry for the confusion.
