### ISSUE TITLE
SSL-related test failures on master

### ISSUE THREAD

**Issue by davidcornu** [lostisland/faraday#529]
Recent builds on Travis (https://travis-ci.org/lostisland/faraday/jobs/81766924) have been encountering the following errors:

```
  1) Failure:
Adapters::EMHttpTest#test_proxy_auth_fail [/home/travis/build/lostisland/faraday/test/adapters/integration.rb:212]:
--- expected
+++ actual
@@ -1 +1 @@
-"407 \"Proxy Authentication Required \""
+"connection closed by server"



  2) Failure:
Adapters::EMSynchronyTest#test_proxy_auth_fail [/home/travis/build/lostisland/faraday/test/adapters/integration.rb:206]:
[Faraday::ConnectionFailed] exception expected, not
Class: <RuntimeError>
Message: <"connection closed by server">
---Backtrace---
/home/travis/build/lostisland/faraday/lib/faraday/adapter/em_synchrony.rb:55:in `call'
/home/travis/build/lostisland/faraday/lib/faraday/response.rb:8:in `call'
/home/travis/build/lostisland/faraday/lib/faraday/request/url_encoded.rb:15:in `call'
/home/travis/build/lostisland/faraday/lib/faraday/request/multipart.rb:14:in `call'
/home/travis/build/lostisland/faraday/lib/faraday/rack_builder.rb:139:in `build_response'
/home/travis/build/lostisland/faraday/lib/faraday/connection.rb:377:in `run_request'
/home/travis/build/lostisland/faraday/lib/faraday/connection.rb:140:in `get'
/home/travis/build/lostisland/faraday/test/adapters/integration.rb:207:in `block in test_proxy_auth_fail'
---------------
```

These match with entries such as these in `log/test.log`

```
[2015-09-23 12:49:52] ERROR OpenSSL::SSL::SSLError: SSL_accept SYSCALL returned=5 errno=0 state=SSLv3 read client certificate A
	/home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/openssl/ssl.rb:236:in `accept'
```

```
[2015-09-23 12:49:54] ERROR OpenSSL::SSL::SSLError: SSL_accept returned=1 errno=0 state=SSLv3 read client certificate A: tlsv1 alert unknown ca
	/home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/openssl/ssl.rb:236:in `accept'
```

However, there are more entries than test errors which either suggests the EventMachine adapters handle these differently or that the other adapters lack coverage for this particular case.

**Comment by mislav** [comment]
Thanks for reporting! I worked around these failures in ab9a0fb4ad24c0740ccc4552d98af15c38b01475
