### ISSUE TITLE
Faraday makes same request twice

### ISSUE THREAD

**Issue by volkanunsal** [lostisland/faraday#542]
I'm battling with a strange loop. The issue is Sawyer makes a POST request, and Faraday makes it twice. The second time it uses the response of the body of the first request. I put a pry in the net_http adapter's #call method and pulled a backtrace when the second request gets made. This is what it looks like:

```
/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
/faraday-0.9.2/lib/faraday/response/logger.rb:24:in `call'
/faraday-0.9.2/lib/faraday/request/url_encoded.rb:15:in `call'
/faraday-0.9.2/lib/faraday/adapter/net_http.rb:57:in `call'
/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
/faraday-0.9.2/lib/faraday/connection.rb:376:in `run_request'
/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
/sawyer-0.6.0/lib/sawyer/agent.rb:94:in `call'
```

So in summary...wtf is going on here?

**Comment by volkanunsal** [comment]
I also tried it with excon adapter. Once again two requests. The first request is made by net_http:

```
/faraday-0.9.2/lib/faraday/adapter/excon.rb:14:in `call'
/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
/faraday-0.9.2/lib/faraday/response/logger.rb:24:in `call'
/faraday-0.9.2/lib/faraday/request/url_encoded.rb:15:in `call'
/faraday-0.9.2/lib/faraday/adapter/net_http.rb:57:in `call'
/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
/faraday-0.9.2/lib/faraday/connection.rb:376:in `run_request'
/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
/sawyer-0.6.0/lib/sawyer/agent.rb:94:in `call'
```

**Comment by Zorbash** [comment]
@volkanunsal are you still interested in resolving this issue? Care to provide code capable of reproducing it? (repo/gist).

**Comment by volkanunsal** [comment]
Hi @Zorbash I don't have the code example for this anymore. I recall I ended up using Faraday directly to fix the issue.
