### ISSUE TITLE
Faraday::SSLError with some domains

### ISSUE THREAD

**Issue by vkarampinis** [lostisland/faraday#558]
Hello there.
Can someone explain why I am getting this error ?

```
require "faraday"
require "openssl"

connection = Faraday.new "https://data.nasdaq.com:443", :ssl => {
  :verify => false
}

response = connection.get "/"
body = response.body
```

And the error output is:

```
/Users/Oden/.rbenv/versions/2.2.3/lib/ruby/2.2.0/net/http.rb:923:in `connect': SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A (Faraday::SSLError)
    from /Users/Oden/.rbenv/versions/2.2.3/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
    from /Users/Oden/.rbenv/versions/2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'
    from /Users/Oden/.rbenv/versions/2.2.3/lib/ruby/2.2.0/net/http.rb:923:in `connect'
    from /Users/Oden/.rbenv/versions/2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
    from /Users/Oden/.rbenv/versions/2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'
    from /Users/Oden/.rbenv/versions/2.2.3/lib/ruby/2.2.0/net/http.rb:1375:in `request'
    from /Users/Oden/.rbenv/versions/2.2.3/lib/ruby/2.2.0/net/http.rb:1133:in `get'
    from /Users/Oden/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:80:in `perform_request'
    from /Users/Oden/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
    from /Users/Oden/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
    from /Users/Oden/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
    from /Users/Oden/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/request/url_encoded.rb:15:in `call'
    from /Users/Oden/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
    from /Users/Oden/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
    from /Users/Oden/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
    from test.rb:8:in `<main>'
```

**Comment by iMacTia** [comment]
Hi @vkarampinis, sorry for the laaaaate response.
Apparently the server you're trying to contact only supports specific types of SSL.
You usually set that in Net::HTTP with `#ssl_version` but you should be able to do that with the `ssl.version` option:

```ruby
connection = Faraday.new "https://data.nasdaq.com:443", :ssl => {
  :verify => false,
  :version => '<version>' # put your version here, e.g. 'SSLv2'
}
```

And that will be catched [here](https://github.com/lostisland/faraday/blob/f994b054f9c4eb3e1200f8fb4f8da89a21d3d346/lib/faraday/adapter/net_http.rb#L106)
