### ISSUE TITLE
Faraday::ConnectionFailed: easy handle already used in multi handle

### ISSUE THREAD

**Issue by NaixSpirit** [lostisland/faraday#626]
After runing Sidekiq and Elasticsearch-rb in 2 threads, I got something wrong
is Faraday not thread safe? if I run the some test in 1 thread, it will not exist

ruby version: ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]  
rails version: 4.2.4  
faraday version: 0.9.2  
elasticsearch-api version: 2.0.0
curl version: curl 7.49.1 (x86_64-apple-darwin16.0) libcurl/7.49.1 SecureTransport zlib/1.2.8

```shell
2016-11-14T07:18:12.150Z 29850 TID-oxqw1ivvo WARN: {"class":"StorageSystemSkuJob","args":["bulk_sell_out",[5,6,7,8,9],"2016-11-14","2016-11-14"],"retry":5,"queue":"elastic_update","jid":"cfddd0b3d11146a63c2cbd5f","created_at":1479107886.726356,"enqueued_at":1479107886.7264152,"error_message":"easy handle already used in multi handle","error_class":"Faraday::ConnectionFailed","failed_at":1479107892.149398,"retry_count":0}
2016-11-14T07:18:12.150Z 29850 TID-oxqw1ivvo WARN: Faraday::ConnectionFailed: easy handle already used in multi handle
2016-11-14T07:18:12.150Z 29850 TID-oxqw1ivvo WARN: /Users/Spirit/.rvm/gems/ruby-2.3.1/gems/patron-0.5.0/lib/patron/session.rb:216:in `handle_request'
/Users/Spirit/.rvm/gems/ruby-2.3.1/gems/patron-0.5.0/lib/patron/session.rb:216:in `request'
/Users/Spirit/.rvm/gems/ruby-2.3.1/gems/faraday-0.9.2/lib/faraday/adapter/patron.rb:33:in `call'
/Users/Spirit/.rvm/gems/ruby-2.3.1/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
/Users/Spirit/.rvm/gems/ruby-2.3.1/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
/Users/Spirit/.rvm/gems/ruby-2.3.1/gems/elasticsearch-transport-2.0.0/lib/elasticsearch/transport/transport/http/faraday.rb:21:in `block in perform_request'
/Users/Spirit/.rvm/gems/ruby-2.3.1/gems/elasticsearch-transport-2.0.0/lib/elasticsearch/transport/transport/base.rb:257:in `perform_request'
/Users/Spirit/.rvm/gems/ruby-2.3.1/gems/elasticsearch-transport-2.0.0/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
/Users/Spirit/.rvm/gems/ruby-2.3.1/gems/elasticsearch-transport-2.0.0/lib/elasticsearch/transport/client.rb:128:in `perform_request'
/Users/Spirit/.rvm/gems/ruby-2.3.1/gems/elasticsearch-api-2.0.0/lib/elasticsearch/api/actions/index.rb:103:in `index'
/Users/Spirit/.rvm/gems/ruby-2.3.1/gems/elasticsearch-model-0.1.9/lib/elasticsearch/model/indexing.rb:336:in `index_document'
```

**Comment by NaixSpirit** [comment]
some issue with https://github.com/elastic/elasticsearch-rails/issues/537

fix it use https://github.com/elastic/elasticsearch-rails/issues/537#issuecomment-224338131
