### ISSUE TITLE
Faraday with HTTPClient throws SocketError instead of Faraday::ConnectionFailed

### ISSUE THREAD

**Issue by abeger** [lostisland/faraday#702]
```ruby
require 'faraday'
require 'httpclient'

conn = Faraday.new(url: 'http://garbage') do |faraday|
  faraday.request :url_encoded
  faraday.adapter :httpclient
end

conn.get('/')
```

The above code fails with a `SocketError`:

```
/path/to/httpclient-2.8.3/lib/httpclient/session.rb:625:in `rescue in create_socket': getaddrinfo: nodename nor servname provided, or not known (garbage:80) (SocketError)
	from /path/to/httpclient-2.8.3/lib/httpclient/session.rb:607:in `create_socket'
	from /path/to/httpclient-2.8.3/lib/httpclient/session.rb:755:in `block in connect'
	from /path/to/ruby/2.3.0/timeout.rb:91:in `block in timeout'
	from /path/to/ruby/2.3.0/timeout.rb:101:in `timeout'
	from /path/to/httpclient-2.8.3/lib/httpclient/session.rb:748:in `connect'
	from /path/to/httpclient-2.8.3/lib/httpclient/session.rb:511:in `query'
	from /path/to/httpclient-2.8.3/lib/httpclient/session.rb:177:in `query'
	from /path/to/httpclient-2.8.3/lib/httpclient.rb:1242:in `do_get_block'
	from /path/to/httpclient-2.8.3/lib/httpclient.rb:1019:in `block in do_request'
	from /path/to/httpclient-2.8.3/lib/httpclient.rb:1133:in `protect_keep_alive_disconnected'
	from /path/to/httpclient-2.8.3/lib/httpclient.rb:1014:in `do_request'
	from /path/to/httpclient-2.8.3/lib/httpclient.rb:856:in `request'
	from /path/to/faraday-0.12.1/lib/faraday/adapter/httpclient.rb:38:in `call'
	from /path/to/faraday-0.12.1/lib/faraday/request/url_encoded.rb:15:in `call'
	from /path/to/faraday-0.12.1/lib/faraday/rack_builder.rb:139:in `build_response'
	from /path/to/faraday-0.12.1/lib/faraday/connection.rb:386:in `run_request'
	from /path/to/faraday-0.12.1/lib/faraday/connection.rb:149:in `get'
	from faraday_example.rb:9:in `<main>'
```

Should this fire off a `Faraday::ConnectionFailed` error instead?

**Comment by abeger** [comment]
I've tested out the code with a few different adapters to put the above issue in context and it looks like `Faraday::ConnectionFailed` is the appropriate thing to be thrown in this case:

```ruby
faraday_adapter :net_http
```

```
/path/to/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect': Failed to open TCP connection to garbage:80 (getaddrinfo: nodename nor servname provided, or not known) (Faraday::ConnectionFailed)
	from /path/to/ruby/2.3.0/net/http.rb:879:in `block in connect'
	from /path/to/ruby/2.3.0/timeout.rb:91:in `block in timeout'
	from /path/to/ruby/2.3.0/timeout.rb:101:in `timeout'
	from /path/to/ruby/2.3.0/net/http.rb:878:in `connect'
	from /path/to/ruby/2.3.0/net/http.rb:863:in `do_start'
	from /path/to/ruby/2.3.0/net/http.rb:852:in `start'
	from /path/to/ruby/2.3.0/net/http.rb:1398:in `request'
	from /path/to/ruby/2.3.0/net/http.rb:1156:in `get'
	from /path/to/faraday-0.12.1/lib/faraday/adapter/net_http.rb:78:in `perform_request'
	from /path/to/faraday-0.12.1/lib/faraday/adapter/net_http.rb:38:in `block in call'
	from /path/to/faraday-0.12.1/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
	from /path/to/faraday-0.12.1/lib/faraday/adapter/net_http.rb:33:in `call'
	from /path/to/faraday-0.12.1/lib/faraday/request/url_encoded.rb:15:in `call'
	from /path/to/faraday-0.12.1/lib/faraday/rack_builder.rb:139:in `build_response'
	from /path/to/faraday-0.12.1/lib/faraday/connection.rb:386:in `run_request'
	from /path/to/faraday-0.12.1/lib/faraday/connection.rb:149:in `get'
	from faraday_example.rb:9:in `<main>'
```

```ruby
faraday_adapter :patron
```

```
/path/to/patron-0.8.0/lib/patron/session.rb:328:in `handle_request': Could not resolve host: garbage (Faraday::ConnectionFailed)
	from /path/to/patron-0.8.0/lib/patron/session.rb:328:in `request'
	from /path/to/faraday-0.12.1/lib/faraday/adapter/patron.rb:28:in `call'
	from /path/to/faraday-0.12.1/lib/faraday/request/url_encoded.rb:15:in `call'
	from /path/to/faraday-0.12.1/lib/faraday/rack_builder.rb:139:in `build_response'
	from /path/to/faraday-0.12.1/lib/faraday/connection.rb:386:in `run_request'
	from /path/to/faraday-0.12.1/lib/faraday/connection.rb:149:in `get'
	from faraday_example.rb:9:in `<main>'
```

```ruby
faraday_adapter :excon
```

```
/path/to/excon-0.57.0/lib/excon/socket.rb:101:in `getaddrinfo': getaddrinfo: nodename nor servname provided, or not known (SocketError) (Faraday::ConnectionFailed)
	from /path/to/excon-0.57.0/lib/excon/socket.rb:101:in `connect'
	from /path/to/excon-0.57.0/lib/excon/socket.rb:29:in `initialize'
	from /path/to/excon-0.57.0/lib/excon/connection.rb:405:in `new'
	from /path/to/excon-0.57.0/lib/excon/connection.rb:405:in `socket'
	from /path/to/excon-0.57.0/lib/excon/connection.rb:100:in `request_call'
	from /path/to/excon-0.57.0/lib/excon/middlewares/mock.rb:48:in `request_call'
	from /path/to/excon-0.57.0/lib/excon/middlewares/instrumentor.rb:26:in `request_call'
	from /path/to/excon-0.57.0/lib/excon/middlewares/base.rb:16:in `request_call'
	from /path/to/excon-0.57.0/lib/excon/middlewares/base.rb:16:in `request_call'
	from /path/to/excon-0.57.0/lib/excon/middlewares/base.rb:16:in `request_call'
	from /path/to/excon-0.57.0/lib/excon/connection.rb:249:in `request'
	from /path/to/faraday-0.12.1/lib/faraday/adapter/excon.rb:50:in `call'
	from /path/to/faraday-0.12.1/lib/faraday/request/url_encoded.rb:15:in `call'
	from /path/to/faraday-0.12.1/lib/faraday/rack_builder.rb:139:in `build_response'
	from /path/to/faraday-0.12.1/lib/faraday/connection.rb:386:in `run_request'
	from /path/to/faraday-0.12.1/lib/faraday/connection.rb:149:in `get'
	from faraday_example.rb:9:in `<main>'
```

```ruby
faraday_adapter :em_http # This might be the wrong way? not sure
```

```
/path/to/faraday-0.12.1/lib/faraday/adapter/em_http.rb:172:in `raise_error': unable to resolve server address: Undefined error: 0 (Faraday::ClientError)
	from /path/to/faraday-0.12.1/lib/faraday/adapter/em_http.rb:113:in `perform_request'
	from /path/to/faraday-0.12.1/lib/faraday/adapter/em_http.rb:90:in `call'
	from /path/to/faraday-0.12.1/lib/faraday/request/url_encoded.rb:15:in `call'
	from /path/to/faraday-0.12.1/lib/faraday/rack_builder.rb:139:in `build_response'
	from /path/to/faraday-0.12.1/lib/faraday/connection.rb:386:in `run_request'
	from /path/to/faraday-0.12.1/lib/faraday/connection.rb:149:in `get'
	from faraday_example.rb:9:in `<main>'
```

**Comment by iMacTia** [comment]
Hi @abeger and thanks for the Issue report.
I agree it would be better if Faraday intercepts the SocketError and re-raises it as a `Faraday::ConnectionFailed`.
I think we're simply missing a rescue here: https://github.com/lostisland/faraday/blob/master/lib/faraday/adapter/httpclient.rb#L45

I'll mark this for next release, should be an easy fix with your how-to-reproduce snippet

**Comment by abeger** [comment]
Thanks!
