### ISSUE TITLE
Undefined Method 'merge' for nil. ActiveSupport 4.2.9 and Faraday > 0.10

### ISSUE THREAD

**Issue by kjbkjb** [lostisland/faraday#710]
Ran across an error while upgrading to Rails 4.2.9, faraday 0.10.1 -> 0.12.1.

```
rest.foundation" event. NoMethodError: undefined method `merge' for nil:NilClass ["/gems/faraday-0.12.1/lib/faraday/options.rb:52:in `block in merge!'",
"/gems/faraday-0.12.1/lib/faraday/options.rb:14:in `block in each'",
"/gems/faraday-0.12.1/lib/faraday/options.rb:13:in `each'",
"/gems/faraday-0.12.1/lib/faraday/options.rb:13:in `each'",
"/gems/faraday-0.12.1/lib/faraday/options.rb:49:in `merge!'",
"/gems/activesupport-4.2.9/lib/active_support/subscriber.rb:97:in `finish'",
"/gems/activesupport-4.2.9/lib/active_support/log_subscriber.rb:83:in `finish'",
"/gems/activesupport-4.2.9/lib/active_support/notifications/fanout.rb:102:in `finish'",
"/gems/activesupport-4.2.9/lib/active_support/notifications/fanout.rb:46:in `block in finish'",
"/gems/activesupport-4.2.9/lib/active_support/notifications/fanout.rb:46:in `each'",
"/gems/activesupport-4.2.9/lib/active_support/notifications/fanout.rb:46:in `finish'",
"/gems/activesupport-4.2.9/lib/active_support/notifications/instrumenter.rb:36:in `finish'",
"/gems/activesupport-4.2.9/lib/active_support/notifications/instrumenter.rb:25:in `instrument'",
"/gems/activesupport-4.2.9/lib/active_support/notifications.rb:164:in `instrument'",
"/gems/faraday-0.12.1/lib/faraday/request/instrumentation.rb:31:in `call'",
"/gems/faraday-0.12.1/lib/faraday/request/url_encoded.rb:15:in `call'",
"/gems/faraday-0.12.1/lib/faraday/rack_builder.rb:139:in `build_response'",
"/gems/faraday-0.12.1/lib/faraday/connection.rb:386:in `run_request'",
"/gems/[[redacted]]/lib/tartarus/request.rb:18:in `run'",
```

Where the tartarus/request code:

```
      Faraday.new(url: url) do |faraday|
        faraday.request :url_encoded
        faraday.request :instrumentation, name: 'rest.foundation'
        faraday.adapter Faraday.default_adapter
      end
```

Here is the line:
https://github.com/lostisland/faraday/blob/master/lib/faraday/options.rb#L52

Still digging into it here, but thought I'd bring this to you fine folks.

**Comment by iMacTia** [comment]
Hi @kjbkjb, thanks for reporting this!
You might have found an edge-case bug on the `merge!` function (which was recently introduced).
I'll have a quick look and get back to you

**Comment by iMacTia** [comment]
Quick update: that was indeed a bug.
I was able to reproduce it with a test and fix it.
Apparently related with the `instrumentation` middleware.

**Comment by kjbkjb** [comment]
Awesome, thanks Mattia

**Comment by iMacTia** [comment]
@kjbkjb I've opened #711 which should fix your issue.
Any chance you can give it a quick shot with your app?

**Comment by kjbkjb** [comment]
👀

**Comment by kjbkjb** [comment]
👍  Looks good on my side. Exceptions stopped.
