### ISSUE TITLE
Nil header value in request block causes NoMethodError in 0.9.x

### ISSUE THREAD

**Issue by f3ndot** [lostisland/faraday#727]
Apologies if duplicate, couldn't find anything with some basic issue searching.

* Ruby 2.3.0
* Faraday 0.9.2

When merging in headers with Nil values to the request block causes an exception:

## Steps to Reproduce

```ruby
connection = Faraday.new(url: 'http://example.com') do |faraday|
  faraday.response :logger, ::Logger.new(STDOUT), bodies: true
  faraday.adapter Faraday.default_adapter
end
connection.post do |request|
  request.url '/some/path'
  request.params = {}
  request.headers.merge!({'X-Some-Header' => nil})
  request.body = "{}"
  request
end
```

Note changing the header value to a string, no exception is raised.

## Expected

A successful response with `X-Some-Header` header absent in the request to the URL.

## Actual

```
NoMethodError: undefined method `strip' for nil:NilClass
	from /Users/justinbull/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http/header.rb:18:in `block in initialize_http_header'
	from /Users/justinbull/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http/header.rb:16:in `each'
	from /Users/justinbull/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http/header.rb:16:in `initialize_http_header'
	from /Users/justinbull/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http/generic_request.rb:44:in `initialize'
	from /Users/justinbull/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:62:in `new'
	from /Users/justinbull/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:62:in `create_request'
	from /Users/justinbull/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:82:in `perform_request'
	from /Users/justinbull/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from /Users/justinbull/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	from /Users/justinbull/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
	from /Users/justinbull/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
	from /Users/justinbull/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/response/logger.rb:24:in `call'
	from /Users/justinbull/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/justinbull/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /Users/justinbull/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
	from (irb):21
```

**Comment by f3ndot** [comment]
The bug is not present in Faraday v0.12.1

**Comment by pbalduino** [comment]
Hi there

I'm getting this error when the response has status 500.

```
NoMethodError - undefined method `map' for nil:NilClass:
  faraday (0.12.1) lib/faraday/response/logger.rb:42:in `dump_headers'
  faraday (0.12.1) lib/faraday/response/logger.rb:31:in `block in on_complete'
  /Users/pliniomarcelino/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/logger.rb:427:in `add'
  /Users/pliniomarcelino/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/logger.rb:455:in `debug'
  /Users/pliniomarcelino/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/forwardable.rb:189:in `debug'
  faraday (0.12.1) lib/faraday/response/logger.rb:31:in `on_complete'
  faraday (0.12.1) lib/faraday/response.rb:9:in `block in call'
  faraday (0.12.1) lib/faraday/response.rb:61:in `on_complete'
  faraday (0.12.1) lib/faraday/response.rb:8:in `call'
  faraday (0.12.1) lib/faraday/response/logger.rb:26:in `call'
  faraday (0.12.1) lib/faraday/rack_builder.rb:139:in `build_response'
  faraday (0.12.1) lib/faraday/connection.rb:386:in `run_request'
  faraday (0.12.1) lib/faraday/connection.rb:149:in `get'
  lib/service_now.rb:16:in `find_by_login'
```

**Comment by iMacTia** [comment]
Hi @pbalduino, this issue shouldn't touch Faraday 0.12.1 so I believe you're having a different issue here.
Please open a separate PR and provide as much information as you can (e.g. your connection initialisation stack)

**Comment by iMacTia** [comment]
Closing as `wontfix` as explained in #739
